name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'samples/**'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'samples/**'
      - 'LICENSE'

jobs:
  test_suite:
    name: Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: getting go version from go.mod
        id: go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

      - name: setting up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: Run suite
        run: |
          make test